# Generated by Django 3.1 on 2020-08-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Tutorials',
        ),
    ]
