# Generated by Django 3.1 on 2020-08-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cSite', '0002_auto_20200816_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorials',
            new_name='Tutorial',
        ),
    ]
